generate release and build tars

diff --git a/vir b/vir
--- a/vir
+++ b/vir
@@ -58,6 +58,125 @@ run_app() {
   fi
 }
 
+build_release() {
+  local branch_name=$(git rev-parse --abbrev-ref HEAD)
+  echo Updating Release Number
+  while read line
+  do
+      local build_no=`expr $line + 1`
+  done < "deployment/build_no"
+
+  while read line
+  do
+      local major=$line
+  done < "deployment/major_ver"
+
+  while read line
+  do
+      local minor=$line
+  done < "deployment/minor_ver"
+
+  echo $build_no > "deployment/build_no"
+
+  local release="v$major.$minor.$build_no-$branch_name"
+
+  if [[ -f "apps/shared/include/version.hrl" ]]; then
+    echo "-define(VERSION, \"$release\")." > apps/shared/include/version.hrl
+  fi
+
+  echo Building Release $release
+  if [[ $DIRTYRELEASE -eq 1 ]]; then
+    make -j apps
+  else
+    make clean-all
+    make
+  fi
+  make rel
+
+  # TODO: Deal with native deps if there are any
+  echo Making BoM and updating Git with new release tag
+  build_bill_of_materials $release "deployment/bill_of_materials"
+
+  git add deployment/build_no
+  git add deployment/bill_of_materials.txt
+  git add deployment/bill_of_materials.info
+
+  ls -d apps/*/include | xargs -n 1 git add
+
+  git tag $release
+  git commit -m "Automated build number increase: $build_no"
+  git push --tags
+  git push
+
+  echo Git updated for version $release
+  echo Building tars and publishing
+  build_tars $release
+}
+
+build_bill_of_materials() {
+  local release=$1
+  local output=$2
+  local logtotxt="$(pwd)/$output.txt"
+  local logtoinfo="$(pwd)/$output.info"
+
+  echo "BoM for release $release" > $logtotxt
+  echo "Built on: $(hostname) by $(id -un)" >> $logtotxt
+  echo "Date: $(date)" >> $logtotxt
+  echo >> $logtotxt
+  echo >> $logtotxt
+  echo "Root project: $(git remote -v)" >> $logtotxt
+  git log -n 1 >> $logtotxt
+  echo >> $logtotxt
+  echo -e "base\t$release\t$(git remote -v | head -1 | awk  '{print $2}')\t$(git rev-parse HEAD)" > $logtoinfo
+
+  local all_deps=$(find deps -mindepth 1 -maxdepth 1 -type d | sort)
+
+  for dep in $all_deps ; do
+    pushd $dep > /dev/null
+    local this_dep=${dep##*/}
+    echo "Git tag for dependency $this_dep" >> $logtotxt
+    echo "pulled from $(git remote -v)" >> $logtotxt
+    git log -n 1 >> $logtotxt
+    echo >> $logtotxt
+    echo -e "dep\t$this_dep\t$(git remote -v | head -1 | awk  '{print $2}')\t$(git rev-parse HEAD)" >> $logtoinfo
+    popd > /dev/null
+  done
+}
+
+build_tars() {
+  local git_tag=$1
+  local releases_folder="$PWD/releases"
+
+  mkdir -p $releases_folder
+
+  for relx_file in $(find "$PWD/apps" -name "relx.config")
+  do
+    local app_dir=$(dirname "$relx_file")
+    pushd $app_dir > /dev/null
+    build_tar $releases_folder $git_tag
+    popd
+  done
+}
+
+build_tar() {
+  local releases_folder=$1
+  local git_tag=$2
+
+  local app=${PWD##*/}
+  local tar_dir="${app}_release_$git_tag"
+  local tar_name="${tar_dir}.tar.gz"
+  local autorun_name="${tar_dir}.run"
+
+  echo Building $app Archive...
+  rm -f $tar_name
+  mv _rel/$app $tar_dir
+  tar cfz $tar_name $tar_dir/  || { echo "Tar failed"; exit 1; }
+  mv $tar_name $releases_folder
+  mv $tar_dir _rel/$app
+  echo done
+}
+
+
 init() {
   mkdir -p $TARGET_DIR
   if [[ "$(ls -A $TARGET_DIR)" ]]; then
@@ -90,6 +209,7 @@ OPTIND=2
 SOURCEDIR=$HOME/.vir
 TEMPLATEDIR=$SOURCEDIR/templates
 RUN_MODE=''
+DIRTYRELEASE=0
 COOKIE='cookie'
 KERNEL='-kernel inet_dist_listen_min 9100 inet_dist_listen_max 9105'
 
@@ -141,6 +261,21 @@ case "$COMMAND" in
     shift $(($OPTIND - 1))
     APP_NAME=$1
     run_app
+    ;;
+  "release")
+    while getopts ":d" option; do
+      case "$option" in
+        d)
+          DIRTYRELEASE=1
+          ;;
+        ?)
+          echo "Error: unknown option -$OPTARG"
+          usage
+          exit 1
+          ;;
+      esac
+    done
+    build_release
     ;;
   *)
     usage
