Added update_deps function

diff --git a/vir b/vir
--- a/vir
+++ b/vir
@@ -212,6 +212,28 @@ init() {
   fi
 }
 
+get_latest() {
+  pushd $1 > /dev/null
+  HeadName=`git rev-parse --abbrev-ref HEAD`
+  echo "On branch $HeadName"
+  if [ $HeadName == "HEAD" ] ; then
+    git checkout master
+  fi
+  git pull
+  popd > /dev/null
+}
+
+update_deps() {
+  shopt -s nullglob
+  deps_to_process=(deps/*$DEPS_PATTERN*/)
+  shopt -u nullglob
+
+  for dep in $deps_to_process ; do
+    echo Updating $dep
+    get_latest $dep
+  done;
+}
+
 usage() {
   local cmd=$1
   case $cmd in
@@ -327,6 +349,27 @@ case "$COMMAND" in
         exit 1
       fi
       init $1
+    ;;
+  "update_deps")
+    while getopts ":d" option; do
+      case "$option" in
+        d)
+          TARGET_DIR=$OPTARG
+          ;;
+        ?)
+          echo "Error: unknown option -$OPTARG"
+          usage "update_deps"
+          exit 1
+          ;;
+      esac
+    done
+    shift $(($OPTIND - 1))
+    DEPS_PATTERN=$1
+    if [[ -z $DEPS_PATTERN ]]; then
+      usage "update_deps"
+      exit 1
+    fi
+    update_deps $DEPS_PATTERN
     ;;
   "boot")
     make_bootscript
